import { SchemaDefinition, ValidationRules } from '@/app/lib/interface';
import { League, PredictionResult, User } from '@prisma/client';

type PredictionFormData = {
    sporttype: string;
    league: string;
    homeTeam: string;
    awayTeam: string;
    tip: string;
    analysis?: string;
    odds?: number;
    result: PredictionResult;
    publishedAt: Date;
    createdBy?: User;
    userId: string;
    isFree: boolean;
    league_rel?: League;
    validation?: ValidationRules
};


export const sportTypeOptions = [
    {
        label: 'Soccer', league: [
            { label: 'Premier League', value: 'premier-league' },
            { label: 'La Liga', value: 'la-liga' },
            { label: 'Bundesliga', value: 'bundesliga' },
            { label: 'Serie A', value: 'serie-a' },
            { label: 'Ligue 1', value: 'ligue-1' },
            { label: 'MLS', value: 'mls' },
            { label: 'Eredivisie', value: 'eredivisie' },
            { label: 'Primeira Liga', value: 'primeira-liga' },
            { label: 'Championship', value: 'championship' },
            { label: 'Scottish Premiership', value: 'scottish-premiership' },
            { label: 'Super Lig', value: 'super-lig' },
            { label: 'Russian Premier League', value: 'russian-premier-league' },
            { label: 'Chinese Super League', value: 'chinese-super-league' },
            { label: 'J1 League', value: 'j1-league' },
            { label: 'A-League', value: 'a-league' },
            { label: 'MLS Next Pro', value: 'mls-next-pro' },
            { label: 'USL Championship', value: 'usl-championship' },
            { label: 'Liga MX', value: 'liga-mx' },
            { label: 'Copa Libertadores', value: 'copa-libertadores' },
            { label: 'Copa Sudamericana', value: 'copa-sudamericana' },
            { label: 'UEFA Champions League', value: 'uefa-champions-league' },
            { label: 'UEFA Europa League', value: 'uefa-europa-league' },
            { label: 'UEFA Conference League', value: 'uefa-conference-league' },
            { label: 'FIFA World Cup', value: 'fifa-world-cup' },
            { label: 'UEFA European Championship', value: 'uefa-european-championship' },
            { label: 'Copa America', value: 'copa-america' },
            { label: 'AFC Asian Cup', value: 'afc-asian-cup' },
            { label: 'CONCACAF Gold Cup', value: 'concacaf-gold-cup' },
            { label: 'Africa Cup of Nations', value: 'africa-cup-of-nations' },
            { label: 'Oceania Nations Cup', value: 'oceania-nations-cup' },
            { label: 'FIFA Club World Cup', value: 'fifa-club-world-cup' },
            { label: 'UEFA Super Cup', value: 'uefa-super-cup' },
            { label: 'CONCACAF Champions League', value: 'concacaf-champions-league' },
            { label: 'AFC Champions League', value: 'afc-champions-league' },
            { label: 'CAF Champions League', value: 'caf-champions-league' },
            { label: 'CONMEBOL Recopa', value: 'conmebol-recopa' },
            { label: 'UEFA Youth League', value: 'uefa-youth-league' },
            { label: 'FIFA U-20 World Cup', value: 'fifa-u20-world-cup' },
            { label: 'FIFA U-17 World Cup', value: 'fifa-u17-world-cup' },
            { label: 'UEFA U21 Championship', value: 'uefa-u21-championship' },
            { label: 'CONCACAF U20 Championship', value: 'concacaf-u20-championship' },
            { label: 'AFC U23 Asian Cup', value: 'afc-u23-asian-cup' },
            { label: 'CAF U23 Africa Cup of Nations', value: 'caf-u23-africa-cup-of-nations' },
            { label: 'CONMEBOL U20 Championship', value: 'conmebol-u20-championship' },
            { label: 'FIFA Women\'s World Cup', value: 'fifa-womens-world-cup' },
            { label: 'UEFA Women\'s Champions League', value: 'uefa-womens-champions-league' },
            { label: 'NWSL', value: 'nwsl' },
            { label: 'FA WSL', value: 'fa-wsl' },
            { label: 'D1 Arkema', value: 'd1-arkema' },
            { label: 'Frau Bundesliga', value: 'frau-bundesliga' },
            { label: 'Primera Division Femenina', value: 'primera-division-femenina' },
            { label: 'Liga F', value: 'liga-f' },
            { label: 'Serie A Femminile', value: 'serie-a-femminile' },
            { label: 'Damallsvenskan', value: 'damallsvenskan' },
            { label: 'W-League', value: 'w-league' },
            { label: 'FA Women\'s Championship', value: 'fa-womens-championship' },
            { label: 'NWSL Challenge Cup', value: 'nwsl-challenge-cup' },
            { label: 'UEFA Women\'s Euro', value: 'uefa-womens-euro' },

        ]
    },
    {
        label: 'Basketball', league: [
            { label: 'NBA', value: 'nba' },
            { label: 'EuroLeague', value: 'euroleague' },
            { label: 'NBL', value: 'nbl' },
            { label: 'WNBA', value: 'wnba' },
            { label: 'CBA', value: 'cba' },
            { label: 'Liga ACB', value: 'liga-acb' },
            { label: 'Liga Nacional', value: 'liga-nacional' },
            { label: 'Lega Basket Serie A', value: 'lega-basket-serie-a' },
            { label: 'Basketball Bundesliga', value: 'basketball-bundesliga' },
            { label: 'French Jeep Elite', value: 'french-jeep-elite' },
            { label: 'VTB United League', value: 'vtb-united-league' },
            { label: 'Adriatic League', value: 'adriatic-league' },
            { label: 'Basketball Champions League', value: 'basketball-champions-league' },
            { label: 'FIBA EuroCup', value: 'fiba-eurocup' },
            { label: 'FIBA Basketball World Cup', value: 'fiba-basketball-world-cup' },
            { label: 'Olympic Basketball Tournament', value: 'olympic-basketball-tournament' },
            { label: 'FIBA Women\'s Basketball World Cup', value: 'fiba-womens-basketball-world-cup' },
            { label: 'WNBA Finals', value: 'wnba-finals' },

        ]
    },
    {
        label: 'Tennis', league: [
            { label: 'ATP Tour', value: 'atp-tour' },
            { label: 'WTA Tour', value: 'wta-tour' },
            { label: 'Grand Slam Tournaments', value: 'grand-slam-tournaments' },
            { label: 'Davis Cup', value: 'davis-cup' },
            { label: 'Fed Cup', value: 'fed-cup' },
            { label: 'Olympic Tennis Tournament', value: 'olympic-tennis-tournament' },
            { label: 'ATP Challenger Tour', value: 'atp-challenger-tour' },
            { label: 'WTA 125K Series', value: 'wta-125k-series' },
            { label: 'ITF World Tennis Tour', value: 'itf-world-tennis-tour' },
            { label: 'Hopman Cup', value: 'hopman-cup' },
            { label: 'Laver Cup', value: 'laver-cup' },
            { label: 'Next Gen ATP Finals', value: 'next-gen-atp-finals' },
            { label: 'WTA Finals', value: 'wta-finals' },
            { label: 'ATP Finals', value: 'atp-finals' },
            { label: 'Davis Cup Finals', value: 'davis-cup-finals' },
            { label: 'Fed Cup Finals', value: 'fed-cup-finals' },
            { label: 'ATP Masters 1000', value: 'atp-masters-1000' },
            { label: 'WTA Premier Mandatory', value: 'wta-premier-mandatory' },
            { label: 'WTA Premier 5', value: 'wta-premier-5' },
            { label: 'ATP 500 Series', value: 'atp-500-series' },
            { label: 'WTA International', value: 'wta-international' },
            { label: 'Challenger Tour Finals', value: 'challenger-tour-finals' },
        ]
    },
    {
        label: 'American Football', league: [
            { label: 'NFL', value: 'nfl' },
            { label: 'CFL', value: 'cfl' },
            { label: 'XFL', value: 'xfl' },
            { label: 'USFL', value: 'usfl' },
            { label: 'NCAA Division I FBS', value: 'ncaa-division-i-fbs' },
            { label: 'NCAA Division I FCS', value: 'ncaa-division-i-fcs' },
            { label: 'NCAA Division II', value: 'ncaa-division-ii' },
            { label: 'NCAA Division III', value: 'ncaa-division-iii' },
            { label: 'NAIA Football', value: 'naia-football' },
            { label: 'European League of Football', value: 'european-league-of-football' },
            { label: 'LFA Mexico', value: 'lfa-mexico' },
            { label: 'Liga de Fútbol Americano Profesional', value: 'liga-de-futbol-americano-profesional' },
            { label: 'Liga Nacional de Fútbol Americano', value: 'liga-nacional-de-futbol-americano' },
            { label: 'Liga Argentina de Fútbol Americano', value: 'liga-argentina-de-futbol-americano' },
            { label: 'Liga Portuguesa de Futebol Americano', value: 'liga-portuguesa-de-futebol-americano' },
            { label: 'Liga Española de Fútbol Americano', value: 'liga-espanola-de-futbol-americano' },
            { label: 'Liga Francesa de Football Américain', value: 'liga-francesa-de-football-americain' },
            { label: 'Liga Italiana di Football Americano', value: 'liga-italiana-di-football-americano' },
            { label: 'Liga Alemana de Football Americano', value: 'liga-alemana-de-football-americano' },
            { label: 'Liga Británica de Fútbol Americano', value: 'liga-britanica-de-futbol-americano' },
            { label: 'Liga Sueca de Fútbol Americano', value: 'liga-sueca-de-futbol-americano' },
            { label: 'Liga Danesa de Fútbol Americano', value: 'liga-danesa-de-futbol-americano' },
            { label: 'Liga Finlandesa de Fútbol Americano', value: 'liga-finlandesa-de-futbol-americano' },
            { label: 'Liga Noruega de Fútbol Americano', value: 'liga-noruega-de-futbol-americano' },
        ]
    },
    {
        label: 'Baseball', league: [
            { label: 'MLB', value: 'mlb' },
            { label: 'Nippon Professional Baseball', value: 'npb' },
            { label: 'Korea Baseball Organization', value: 'kbo' },
            { label: 'Chinese Professional Baseball League', value: 'cpbl' },
            { label: 'Liga Mexicana de Béisbol', value: 'lmb' },
            { label: 'Liga Venezolana de Béisbol Profesional', value: 'lvbp' },
            { label: 'Liga Dominicana de Béisbol Profesional', value: 'lidom' },
            { label: 'Liga de Béisbol Profesional Roberto Clemente', value: 'lbprc' },
            { label: 'Australian Baseball League', value: 'abl' },
            { label: 'European Baseball Championship', value: 'european-baseball-championship' },
            { label: 'World Baseball Classic', value: 'world-baseball-classic' },
            { label: 'Little League World Series', value: 'little-league-world-series' },
            { label: 'College World Series', value: 'college-world-series' },
            { label: 'Cape Cod Baseball League', value: 'cape-cod-baseball-league' },
            { label: 'Atlantic League', value: 'atlantic-league' },
            { label: 'American Association', value: 'american-association' },
            { label: 'Frontier League', value: 'frontier-league' },
            { label: 'Pioneer League', value: 'pioneer-league' },
            { label: 'Pacific Association', value: 'pacific-association' },
            { label: 'Liga de Béisbol Profesional de Panamá', value: 'lbpp' },
            { label: 'Liga de Béisbol Profesional de Colombia', value: 'lbpc' },
            { label: 'Liga de Béisbol Profesional de Nicaragua', value: 'lbpn' },
            { label: 'Liga de Béisbol Profesional de Guatemala', value: 'lbpg' },
        ]
    },
    {
        label: 'Hockey', league: [
            { label: 'NHL', value: 'nhl' },
            { label: 'KHL', value: 'khl' },
            { label: 'AHL', value: 'ahl' },
            { label: 'EIHL', value: 'eihl' },
            { label: 'SHL', value: 'shl' },
            { label: 'Liiga', value: 'liiga' },
            { label: 'DEL', value: 'del' },
            { label: 'NLA', value: 'nla' },
            { label: 'Czech Extraliga', value: 'czech-extraliga' },
            { label: 'Swiss League', value: 'swiss-league' },
            { label: 'IIHF World Championship', value: 'iihf-world-championship' },
            { label: 'Olympic Ice Hockey Tournament', value: 'olympic-ice-hockey-tournament' },
            { label: 'World Junior Ice Hockey Championships', value: 'world-junior-ice-hockey-championships' },
            { label: 'Spengler Cup', value: 'spengler-cup' },
            { label: 'CHL Champions Hockey League', value: 'chl-champions-hockey-league' },
            { label: 'NCAA Division I Ice Hockey', value: 'ncaa-division-i-ice-hockey' },
            { label: 'USHL United States Hockey League', value: 'ushl-united-states-hockey-league' },
            { label: 'OHL Ontario Hockey League', value: 'ohl-ontario-hockey-league' },
            { label: 'WHL Western Hockey League', value: 'whl-western-hockey-league' },
            { label: 'QMJHL Quebec Major Junior Hockey League', value: 'qmjhl-quebec-major-junior-hockey-league' },
            { label: 'ECHL East Coast Hockey League', value: 'echl-east-coast-hockey-league' },
            { label: 'SPHL Southern Professional Hockey League', value: 'sphl-southern-professional-hockey-league' },
            { label: 'FHL Federal Hockey League', value: 'fhl-federal-hockey-league' },
            { label: 'LNAH Ligue Nord-Américaine de Hockey', value: 'lnah-ligue-nord-americaine-de-hockey' },
        ]
    },
    {
        label: 'Rugby', league: [
            { label: 'Rugby Union', value: 'rugby-union' },
            { label: 'Rugby League', value: 'rugby-league' },
            { label: 'Super Rugby', value: 'super-rugby' },
            { label: 'Top 14', value: 'top-14' },
            { label: 'Premiership Rugby', value: 'premiership-rugby' },
            { label: 'Pro14', value: 'pro14' },
            { label: 'Major League Rugby', value: 'major-league-rugby' },
            { label: 'European Rugby Champions Cup', value: 'european-rugby-champions-cup' },
            { label: 'European Rugby Challenge Cup', value: 'european-rugby-challenge-cup' },
            { label: 'Six Nations Championship', value: 'six-nations-championship' },
            { label: 'Rugby World Cup', value: 'rugby-world-cup' },
            { label: 'British and Irish Lions Tour', value: 'british-and-irish-lions-tour' },
            { label: 'Rugby Championship', value: 'rugby-championship' },
            { label: 'Currie Cup', value: 'currie-cup' },
            { label: 'Mitre 10 Cup', value: 'mitre-10-cup' },
            { label: 'National Rugby Championship', value: 'national-rugby-championship' },
            { label: 'European Rugby Sevens Series', value: 'european-rugby-sevens-series' },
            { label: 'World Rugby Sevens Series', value: 'world-rugby-sevens-series' },
            { label: 'Olympic Rugby Sevens Tournament', value: 'olympic-rugby-sevens-tournament' },
            { label: 'Rugby Americas North Championship', value: 'rugby-americas-north-championship' },
            { label: 'Asia Rugby Championship', value: 'asia-rugby-championship' },
            { label: 'Africa Cup', value: 'africa-cup' },
            { label: 'Pacific Nations Cup', value: 'pacific-nations-cup' },
            { label: 'European Nations Cup', value: 'european-nations-cup' },
            { label: 'Rugby Europe Championship', value: 'rugby-europe-championship' },
            { label: 'Rugby Americas South Championship', value: 'rugby-americas-south-championship' },
        ]
    },
    {
        label: 'Cricket', league: [
            { label: 'Indian Premier League', value: 'indian-premier-league' },
            { label: 'Big Bash League', value: 'big-bash-league' },
            { label: 'Pakistan Super League', value: 'pakistan-super-league' },
            { label: 'Caribbean Premier League', value: 'caribbean-premier-league' },
            { label: 'Vitality Blast', value: 'vitality-blast' },
            { label: 'County Championship', value: 'county-championship' },
            { label: 'Sheffield Shield', value: 'sheffield-shield' },
            { label: 'Ranji Trophy', value: 'ranji-trophy' },
            { label: 'Duleep Trophy', value: 'duleep-trophy' },
            { label: 'Deodhar Trophy', value: 'deodhar-trophy' },
            { label: 'Syed Mushtaq Ali Trophy', value: 'syed-mushtaq-ali-trophy' },
            { label: 'Vijay Hazare Trophy', value: 'vijay-hazare-trophy' },
            { label: 'ICC Cricket World Cup', value: 'icc-cricket-world-cup' },
            { label: 'ICC T20 World Cup', value: 'icc-t20-world-cup' },
            { label: 'ICC Champions Trophy', value: 'icc-champions-trophy' },
            { label: 'Asia Cup', value: 'asia-cup' },
            { label: 'Bilateral Series', value: 'bilateral-series' },
            { label: 'Test Series', value: 'test-series' },
            { label: 'ODI Series', value: 'odi-series' },
            { label: 'T20I Series', value: 't20i-series' },
            { label: 'Domestic T20 Leagues', value: 'domestic-t20-leagues' },
            { label: 'Women\'s Cricket', value: 'womens-cricket' },
            { label: 'Women\'s T20 Leagues', value: 'womens-t20-leagues' },
            { label: 'Women\'s ODI Series', value: 'womens-odi-series' },
            { label: 'Women\'s Test Series', value: 'womens-test-series' },

        ]
    },
    {
        label: 'Volleyball', league: [
            { label: 'FIVB Volleyball World Championship', value: 'fivb-volleyball-world-championship' },
            { label: 'FIVB Volleyball Nations League', value: 'fivb-volleyball-nations-league' },
            { label: 'FIVB Beach Volleyball World Tour', value: 'fivb-beach-volleyball-world-tour' },
            { label: 'AVP Pro Beach Volleyball Tour', value: 'avp-pro-beach-volleyball-tour' },
            { label: 'CEV Champions League', value: 'cev-champions-league' },
            { label: 'CEV Cup', value: 'cev-cup' },
            { label: 'CEV Challenge Cup', value: 'cev-challenge-cup' },
            { label: 'NCAA Division I Volleyball Championship', value: 'ncaa-division-i-volleyball-championship' },
            { label: 'NCAA Division II Volleyball Championship', value: 'ncaa-division-ii-volleyball-championship' },
            { label: 'NCAA Division III Volleyball Championship', value: 'ncaa-division-iii-volleyball-championship' },
            { label: 'AVCA Collegiate Beach Volleyball Championship', value: 'avca-collegiate-beach-volleyball-championship' },
            { label: 'FIVB Women\'s Volleyball World Championship', value: 'fivb-womens-volleyball-world-championship' },
            { label: 'FIVB Women\'s Volleyball Nations League', value: 'fivb-womens-volleyball-nations-league' },
            { label: 'FIVB Women\'s Beach Volleyball World Tour', value: 'fivb-womens-beach-volleyball-world-tour' },
            { label: 'AVP Women\'s Pro Beach Volleyball Tour', value: 'avp-womens-pro-beach-volleyball-tour' },
            { label: 'FIVB U21 Volleyball World Championship', value: 'fivb-u21-volleyball-world-championship' },
            { label: 'FIVB U19 Volleyball World Championship', value: 'fivb-u19-volleyball-world-championship' },
            { label: 'FIVB U23 Volleyball World Championship', value: 'fivb-u23-volleyball-world-championship' },
            { label: 'FIVB U21 Beach Volleyball World Championship', value: 'fivb-u21-beach-volleyball-world-championship' },
            { label: 'FIVB U19 Beach Volleyball World Championship', value: 'fivb-u19-beach-volleyball-world-championship' },
        ]
    },
    {
        label: 'Handball', league: [
            { label: 'EHF Champions League', value: 'ehf-champions-league' },
            { label: 'EHF Cup', value: 'ehf-cup' },
            { label: 'EHF Challenge Cup', value: 'ehf-challenge-cup' },
            { label: 'IHF World Championship', value: 'ihf-world-championship' },
            { label: 'IHF World Handball Championship', value: 'ihf-world-handball-championship' },
            { label: 'Olympic Handball Tournament', value: 'olympic-handball-tournament' },
            { label: 'European Handball Championship', value: 'european-handball-championship' },
            { label: 'Pan American Handball Championship', value: 'pan-american-handball-championship' },
            { label: 'Asian Handball Championship', value: 'asian-handball-championship' },
            { label: 'African Handball Championship', value: 'african-handball-championship' },
            { label: 'North American and Caribbean Handball Championship', value: 'north-american-and-caribbean-handball-championship' },
            { label: 'Handball Bundesliga', value: 'handball-bundesliga' },
            { label: 'Ligue Nationale de Handball', value: 'ligue-nationale-de-handball' },
            { label: 'Liga ASOBAL', value: 'liga-asobal' },
            { label: 'Danish Handball League', value: 'danish-handball-league' },
            { label: 'Swedish Handbollsligan', value: 'swedish-handbollsligan' },
        ]
    },
    {
        label: 'Mixed', league: [
            { label: 'Mixed Martial Arts', value: 'mixed-martial-arts' },
            { label: 'Boxing', value: 'boxing' },
            { label: 'Wrestling', value: 'wrestling' },
            { label: 'Judo', value: 'judo' },
            { label: 'Taekwondo', value: 'taekwondo' },
            { label: 'Karate', value: 'karate' },
            { label: 'Kickboxing', value: 'kickboxing' },
            { label: 'Muay Thai', value: 'muay-thai' },
            { label: 'Brazilian Jiu-Jitsu', value: 'brazilian-jiu-jitsu' },
            { label: 'Sambo', value: 'sambo' },
            { label: 'Krav Maga', value: 'krav-maga' },
            { label: 'Capoeira', value: 'capoeira' },
            { label: 'Aikido', value: 'aikido' },
            { label: 'Hapkido', value: 'hapkido' },
            { label: 'Wing Chun', value: 'wing-chun' },
            { label: 'Sanda', value: 'sanda' },
            { label: 'Lethwei', value: 'lethwei' },
            { label: 'Savate', value: 'savate' },
            { label: 'Pencak Silat', value: 'pencak-silat' },
            { label: 'Systema', value: 'systema' },
            { label: 'Ninjutsu', value: 'ninjutsu' },
            { label: 'Jeet Kune Do', value: 'jeet-kune-do' },
            { label: 'Combat Sambo', value: 'combat-sambo' },
        ]
    },
    {
        label: 'Boxing', league: [
            { label: 'WBC', value: 'wbc' },
            { label: 'WBA', value: 'wba' },
            { label: 'IBF', value: 'ibf' },
            { label: 'WBO', value: 'wbo' },
            { label: 'IBO', value: 'ibo' },
            { label: 'The Ring Magazine', value: 'the-ring-magazine' },
            { label: 'World Boxing Super Series', value: 'world-boxing-super-series' },


        ]
    },
    {
        label: 'Golf', league: [
            { label: 'PGA Tour', value: 'pga-tour' },
            { label: 'European Tour', value: 'european-tour' },
            { label: 'LPGA Tour', value: 'lpga-tour' },
            { label: 'Champions Tour', value: 'champions-tour' },
            { label: 'Asian Tour', value: 'asian-tour' },
            { label: 'Sunshine Tour', value: 'sunshine-tour' },
            { label: 'Japan Golf Tour', value: 'japan-golf-tour' },
            { label: 'Ladies European Tour', value: 'ladies-european-tour' },
            { label: 'Korn Ferry Tour', value: 'korn-ferry-tour' },
            { label: 'Omega Dubai Desert Classic', value: 'omega-dubai-desert-classic' },
            { label: 'The Masters Tournament', value: 'the-masters-tournament' },
            { label: 'U.S. Open Championship', value: 'us-open-championship' },
            { label: 'The Open Championship', value: 'the-open-championship' },
            { label: 'PGA Championship', value: 'pga-championship' },
            { label: 'Ryder Cup', value: 'ryder-cup' },
            { label: 'Solheim Cup', value: 'solheim-cup' },
            { label: 'President\'s Cup', value: 'presidents-cup' },
            { label: 'Olympic Golf Tournament', value: 'olympic-golf-tournament' },
            { label: 'World Golf Championships', value: 'world-golf-championships' },
            { label: 'FedEx Cup Playoffs', value: 'fedex-cup-playoffs' },


        ]
    },
    {
        label: 'Motorsport', league: [
            { label: 'Formula 1', value: 'formula-1' },
            { label: 'MotoGP', value: 'motogp' },
            { label: 'NASCAR Cup Series', value: 'nascar-cup-series' },
            { label: 'IndyCar Series', value: 'indycar-series' },
            { label: 'World Rally Championship', value: 'world-rally-championship' },
            { label: 'FIA World Endurance Championship', value: 'fia-world-endurance-championship' },
            { label: 'FIA Formula E Championship', value: 'fia-formula-e-championship' },
            { label: 'Supercars Championship', value: 'supercars-championship' },
            { label: 'DTM Deutsche Tourenwagen Masters', value: 'dtm-deutsche-tourenwagen-masters' },
            { label: 'British Touring Car Championship', value: 'british-touring-car-championship' },
            { label: 'IMSA WeatherTech SportsCar Championship', value: 'imsa-weathertech-sportscar-championship' },
            { label: 'Le Mans 24 Hours', value: 'le-mans-24-hours' },
            { label: 'Monaco Grand Prix', value: 'monaco-grand-prix' },
            { label: 'Indianapolis 500', value: 'indianapolis-500' },
            { label: 'Daytona 500', value: 'daytona-500' },
            { label: 'Tour de France Cycliste', value: 'tour-de-france-cycliste' },
            { label: 'Vuelta a España', value: 'vuelta-a-espana' },
            { label: 'Giro d\'Italia', value: 'giro-ditalia' },
        ]
    },
    {
        label: 'Esports', league: [
            { label: 'League of Legends', value: 'league-of-legends' },
            { label: 'Dota 2', value: 'dota-2' },
            { label: 'Counter-Strike: Global Offensive', value: 'csgo' },
            { label: 'Overwatch', value: 'overwatch' },
            { label: 'Valorant', value: 'valorant' },
            { label: 'Call of Duty', value: 'call-of-duty' },
            { label: 'FIFA', value: 'fifa' },
            { label: 'PUBG', value: 'pubg' },
            { label: 'Apex Legends', value: 'apex-legends' },
            { label: 'Rainbow Six Siege', value: 'rainbow-six-siege' },
            { label: 'StarCraft II', value: 'starcraft-ii' },
            { label: 'Hearthstone', value: 'hearthstone' },
            { label: 'Rocket League', value: 'rocket-league' },
            { label: 'Smite', value: 'smite' },
            { label: 'World of Warcraft', value: 'world-of-warcraft' },
            { label: 'Street Fighter V', value: 'street-fighter-v' },
            { label: 'Tekken 7', value: 'tekken-7' },
        ]
    },
    {
        label: 'Table Tennis', league: [
            { label: 'ITTF World Tour', value: 'ittf-world-tour' },
            { label: 'ITTF World Championships', value: 'ittf-world-championships' },
            { label: 'ITTF World Cup', value: 'ittf-world-cup' },
            { label: 'European Table Tennis Championships', value: 'european-table-tennis-championships' },
            { label: 'Asian Table Tennis Championships', value: 'asian-table-tennis-championships' },
            { label: 'Pan American Table Tennis Championships', value: 'pan-american-table-tennis-championships' },
            { label: 'African Table Tennis Championships', value: 'african-table-tennis-championships' },
            { label: 'Oceania Table Tennis Championships', value: 'oceania-table-tennis-championships' },
            { label: 'National Table Tennis Leagues', value: 'national-table-tennis-leagues' },
            { label: 'Chinese Super League', value: 'chinese-super-league' },
            { label: 'German Bundesliga', value: 'german-bundesliga' },
            { label: 'Japanese T.League', value: 'japanese-t-league' },
            { label: 'Korean Table Tennis League', value: 'korean-table-tennis-league' },
            { label: 'French Table Tennis League', value: 'french-table-tennis-league' },
            { label: 'Spanish Table Tennis League', value: 'spanish-table-tennis-league' },
            { label: 'Italian Table Tennis League', value: 'italian-table-tennis-league' },
            { label: 'Russian Table Tennis League', value: 'russian-table-tennis-league' },
            { label: 'Swedish Table Tennis League', value: 'swedish-table-tennis-league' },
            { label: 'English Table Tennis League', value: 'english-table-tennis-league' },
            { label: 'International Table Tennis Federation (ITTF)', value: 'international-table-tennis-federation' },
        ]
    },
    {
        label: 'Badminton', league: [
            { label: 'BWF World Tour', value: 'bwf-world-tour' },
            { label: 'BWF World Championships', value: 'bwf-world-championships' },
            { label: 'BWF Thomas Cup', value: 'bwf-thomas-cup' },
            { label: 'BWF Uber Cup', value: 'bwf-uber-cup' },
            { label: 'BWF Sudirman Cup', value: 'bwf-sudirman-cup' },
            { label: 'BWF All England Open Badminton Championships', value: 'bwf-all-england-open-badminton-championships' },
            { label: 'BWF Malaysia Open', value: 'bwf-malaysia-open' },
            { label: 'BWF Indonesia Open', value: 'bwf-indonesia-open' },
            { label: 'BWF China Open', value: 'bwf-china-open' },
            { label: 'BWF Japan Open', value: 'bwf-japan-open' },
            { label: 'BWF Korea Open', value: 'bwf-korea-open' },
            { label: 'BWF Denmark Open', value: 'bwf-denmark-open' },
            { label: 'BWF French Open', value: 'bwf-french-open' },
            { label: 'BWF India Open', value: 'bwf-india-open' },
            { label: 'BWF Singapore Open', value: 'bwf-singapore-open' },
            { label: 'BWF Thailand Open', value: 'bwf-thailand-open' },
            { label: 'BWF Hong Kong Open', value: 'bwf-hong-kong-open' },
            { label: 'BWF Australia Open', value: 'bwf-australia-open' },
            { label: 'BWF New Zealand Open', value: 'bwf-new-zealand-open' },
            { label: 'BWF European Championships', value: 'bwf-european-championships' },
            { label: 'BWF Pan American Championships', value: 'bwf-pan-american-championships' },
            { label: 'BWF African Championships', value: 'bwf-african-championships' },
            { label: 'BWF Oceania Championships', value: 'bwf-oceania-championships' },
            { label: 'BWF Junior World Championships', value: 'bwf-junior-world-championships' },
            { label: 'BWF World Junior Mixed Team Championships', value: 'bwf-world-junior-mixed-team-championships' },
        ]
    },
    {
        label: 'Snooker', league: [
            { label: 'World Snooker Tour', value: 'world-snooker-tour' },
            { label: 'World Snooker Championship', value: 'world-snooker-championship' },
            { label: 'UK Championship', value: 'uk-championship' },
            { label: 'Masters', value: 'masters' },
            { label: 'European Masters', value: 'european-masters' },
            { label: 'China Open', value: 'china-open' },
            { label: 'Welsh Open', value: 'welsh-open' },
            { label: 'Scottish Open', value: 'scottish-open' },
            { label: 'Northern Ireland Open', value: 'northern-ireland-open' },
            { label: 'German Masters', value: 'german-masters' },
            { label: 'English Open', value: 'english-open' },
            { label: 'International Championship', value: 'international-championship' },
            { label: 'Shanghai Masters', value: 'shanghai-masters' },
            { label: 'World Cup of Snooker', value: 'world-cup-of-snooker' },
            { label: 'World Seniors Tour', value: 'world-seniors-tour' },
            { label: 'World Women\'s Snooker Tour', value: 'world-womens-snooker-tour' },
            { label: 'World Under-21 Snooker Championship', value: 'world-under-21-snooker-championship' },
            { label: 'World Amateur Snooker Championship', value: 'world-amateur-snooker-championship' },
            { label: 'International Billiards and Snooker Federation (IBSF)', value: 'international-billiards-and-snooker-federation' },

        ]
    },
    {
        label: 'Darts', league: [
            { label: 'PDC World Darts Championship', value: 'pdc-world-darts-championship' },
            { label: 'PDC Premier League Darts', value: 'pdc-premier-league-darts' },
            { label: 'PDC World Matchplay', value: 'pdc-world-matchplay' },
            { label: 'PDC UK Open', value: 'pdc-uk-open' },
            { label: 'PDC European Championship', value: 'pdc-european-championship' },
            { label: 'PDC Grand Slam of Darts', value: 'pdc-grand-slam-of-darts' },
            { label: 'PDC Players Championship Finals', value: 'pdc-players-championship-finals' },
            { label: 'BDO World Darts Championship', value: 'bdo-world-darts-championship' },
            { label: 'BDO World Trophy', value: 'bdo-world-trophy' },
            { label: 'BDO World Masters', value: 'bdo-world-masters' },
            { label: 'WDF World Darts Championship', value: 'wdf-world-darts-championship' },
            { label: 'WDF Europe Cup', value: 'wdf-europe-cup' },
            { label: 'WDF Americas Cup', value: 'wdf-americas-cup' },
            { label: 'WDF Asia-Pacific Cup', value: 'wdf-asia-pacific-cup' },
            { label: 'WDF World Cup', value: 'wdf-world-cup' },
            { label: 'PDC Asian Tour', value: 'pdc-asian-tour' },
            { label: 'PDC Development Tour', value: 'pdc-development-tour' },
            { label: 'PDC Challenge Tour', value: 'pdc-challenge-tour' },
            { label: 'PDC World Series of Darts', value: 'pdc-world-series-of-darts' },
            { label: 'PDC Nordic and Baltic Tour', value: 'pdc-nordic-and-baltic-tour' },
            { label: 'PDC South African Tour', value: 'pdc-south-african-tour' },
            { label: 'PDC North American Tour', value: 'pdc-north-american-tour' },

        ]
    },
    {
        label: 'Cycling', league: [
            { label: 'Tour de France', value: 'tour-de-france' },
            { label: 'Giro d\'Italia', value: 'giro-ditalia' },
            { label: 'Vuelta a España', value: 'vuelta-a-espana' },
            { label: 'UCI Road World Championships', value: 'uci-road-world-championships' },
            { label: 'UCI Track Cycling World Championships', value: 'uci-track-cycling-world-championships' },
            { label: 'UCI Mountain Bike World Championships', value: 'uci-mountain-bike-world-championships' },
            { label: 'UCI Cyclo-cross World Championships', value: 'uci-cyclo-cross-world-championships' },
            { label: 'UCI BMX World Championships', value: 'uci-bmx-world-championships' },
            { label: 'UCI Para-cycling Road World Championships', value: 'uci-para-cycling-road-world-championships' },
            { label: 'UCI Para-cycling Track World Championships', value: 'uci-para-cycling-track-world-championships' },
            { label: 'UCI Para-cycling Mountain Bike World Championships', value: 'uci-para-cycling-mountain-bike-world-championships' },
            { label: 'UCI Para-cycling Cyclo-cross World Championships', value: 'uci-para-cycling-cyclo-cross-world-championships' },
            { label: 'UCI Para-cycling BMX World Championships', value: 'uci-para-cycling-bmx-world-championships' },
            { label: 'UCI Women\'s WorldTour', value: 'uci-womens-worldtour' },
            { label: 'UCI Men\'s WorldTour', value: 'uci-mens-worldtour' },
            { label: 'UCI Continental Circuits', value: 'uci-continental-circuits' },
            { label: 'UCI Gran Fondo World Series', value: 'uci-gran-fondo-world-series' },
            { label: 'UCI Para-cycling World Cup', value: 'uci-para-cycling-world-cup' },
            { label: 'UCI Track Cycling World Cup', value: 'uci-track-cycling-world-cup' },
            { label: 'UCI Mountain Bike World Cup', value: 'uci-mountain-bike-world-cup' },
            { label: 'UCI Cyclo-cross World Cup', value: 'uci-cyclo-cross-world-cup' },
            { label: 'UCI BMX Supercross World Cup', value: 'uci-bmx-supercross-world-cup' },
        ]
    },
    {
        label: 'Athletics', league: [
            { label: 'IAAF World Championships', value: 'iaaf-world-championships' },
            { label: 'Olympic Games Athletics', value: 'olympic-games-athletics' },
            { label: 'Diamond League', value: 'diamond-league' },
            { label: 'IAAF World Indoor Championships', value: 'iaaf-world-indoor-championships' },
            { label: 'IAAF World Cross Country Championships', value: 'iaaf-world-cross-country-championships' },
            { label: 'IAAF World Half Marathon Championships', value: 'iaaf-world-half-marathon-championships' },

        ]
    },
    {
        label: 'Swimming', league: [
            { label: 'FINA World Championships', value: 'fina-world-championships' },
            { label: 'Olympic Games Swimming', value: 'olympic-games-swimming' },
            { label: 'FINA World Cup', value: 'fina-world-cup' },
            { label: 'FINA Swimming World Cup', value: 'fina-swimming-world-cup' },
            { label: 'FINA Diving World Series', value: 'fina-diving-world-series' },
            { label: 'FINA Water Polo World League', value: 'fina-water-polo-world-league' },
            { label: 'FINA Artistic Swimming World Series', value: 'fina-artistic-swimming-world-series' },
            { label: 'FINA Open Water Swimming World Cup', value: 'fina-open-water-swimming-world-cup' },
            { label: 'FINA High Diving World Series', value: 'fina-high-diving-world-series' },
            { label: 'FINA Swimming World Cup Series', value: 'fina-swimming-world-cup-series' },
            { label: 'FINA Diving Grand Prix', value: 'fina-diving-grand-prix' },
            { label: 'FINA Water Polo World Cup', value: 'fina-water-polo-world-cup' },
            { label: 'FINA Artistic Swimming World Cup', value: 'fina-artistic-swimming-world-cup' },
            { label: 'FINA Open Water Swimming Grand Prix', value: 'fina-open-water-swimming-grand-prix' },
            { label: 'FINA High Diving World Cup', value: 'fina-high-diving-world-cup' },

        ]
    },
    {
        label: 'Other', league: [
            { label: 'Other Sports', value: 'other-sports' },
            { label: 'Water Polo', value: 'water-polo' },
            { label: 'Lacrosse', value: 'lacrosse' },
            { label: 'Field Hockey', value: 'field-hockey' },
            { label: 'Rugby Sevens', value: 'rugby-sevens' },
            { label: 'Futsal', value: 'futsal' },
            { label: 'Handball', value: 'handball' },
            { label: 'Ultimate Frisbee', value: 'ultimate-frisbee' },
            { label: 'Bandy', value: 'bandy' },
            { label: 'Curling', value: 'curling' },
            { label: 'Skiing', value: 'skiing' },
            { label: 'Snowboarding', value: 'snowboarding' },
            { label: 'Surfing', value: 'surfing' },
            { label: 'Skateboarding', value: 'skateboarding' },
            { label: 'Rock Climbing', value: 'rock-climbing' },
            { label: 'Martial Arts', value: 'martial-arts' },
            { label: 'Gymnastics', value: 'gymnastics' },
            { label: 'Equestrian', value: 'equestrian' },
            { label: 'Sailing', value: 'sailing' },
            { label: 'Rowing', value: 'rowing' },
            { label: 'Canoeing', value: 'canoeing' },
            { label: 'Kayaking', value: 'kayaking' },
            { label: 'Triathlon', value: 'triathlon' },
            { label: 'Badminton', value: 'badminton' },
            { label: 'Table Tennis', value: 'table-tennis' },
            { label: 'Squash', value: 'squash' },
            { label: 'Cricket', value: 'cricket' },
            { label: 'Baseball', value: 'baseball' },
            { label: 'Softball', value: 'softball' },
            { label: 'Golf', value: 'golf' },
            { label: 'Motorsport', value: 'motorsport' },
            { label: 'Esports', value: 'esports' },
            { label: 'Cycling', value: 'cycling' },
            { label: 'Athletics', value: 'athletics' },
            { label: 'Swimming', value: 'swimming' },
            { label: 'Darts', value: 'darts' },
            { label: 'Snooker', value: 'snooker' },
            { label: 'Boxing', value: 'boxing' },
            { label: 'Mixed Martial Arts', value: 'mixed-martial-arts' },
            { label: 'Wrestling', value: 'wrestling' },
            { label: 'Archery', value: 'archery' },
            { label: 'Shooting', value: 'shooting' },
            { label: 'Fencing', value: 'fencing' },
            { label: 'Judo', value: 'judo' },
            { label: 'Taekwondo', value: 'taekwondo' },
            { label: 'Karate', value: 'karate' },
            { label: 'Kickboxing', value: 'kickboxing' },
            { label: 'Muay Thai', value: 'muay-thai' },
            { label: 'Billiards', value: 'billiards' },
            { label: 'Pool', value: 'pool' },
            { label: 'Bowling', value: 'bowling' },
            { label: 'Luge', value: 'luge' },
            { label: 'Skeleton', value: 'skeleton' },
            { label: 'Bobsleigh', value: 'bobsleigh' },
            { label: 'Speed Skating', value: 'speed-skating' },
            { label: 'Figure Skating', value: 'figure-skating' },
            { label: 'Short Track Speed Skating', value: 'short-track-speed-skating' },
            { label: 'Curling', value: 'curling' },
            { label: 'Ice Dancing', value: 'ice-dancing' },
            { label: 'Synchronized Swimming', value: 'synchronized-swimming' },
            { label: 'Water Skiing', value: 'water-skiing' },
            { label: 'Wakeboarding', value: 'wakeboarding' },
            { label: 'Kiteboarding', value: 'kiteboarding' },
            { label: 'Paragliding', value: 'paragliding' },
            { label: 'Hang Gliding', value: 'hang-gliding' },
        ]
    }
]

export const predictionFormSchema: SchemaDefinition<PredictionFormData> = {
    sporttype: {
        type: 'select',
        label: 'Type of Sport',
        required: true,
        placeholder: 'Select a sport type',
        options: [
            { label: 'Soccar', value: 'Soccar' },
            { label: 'Basketball', value: 'Basketball' },
            { label: 'Tennis', value: 'Tennis' },
            { label: 'American Football', value: 'American Football' },
            { label: 'Baseball', value: 'Baseball' },
            { label: 'Hockey', value: 'Hockey' },
            { label: 'Rugby', value: 'Rugby' },
            { label: 'Cricket', value: 'Cricket' },
            { label: 'Volleyball', value: 'Volleyball' },
            { label: 'Handball', value: 'Handball' },
            { label: 'Mixed Martial Arts', value: 'Mixed Martial Arts' },
            { label: 'Boxing', value: 'Boxing' },
            { label: 'Golf', value: 'Golf' },
            { label: 'Motorsport', value: 'Motorsport' },
            { label: 'Esports', value: 'Esports' },
            { label: 'Table Tennis', value: 'Table Tennis' },
            { label: 'Badminton', value: 'Badminton' },
            { label: 'Snooker', value: 'Snooker' },
            { label: 'Darts', value: 'Darts' },
            { label: 'Cycling', value: 'Cycling' },
            { label: 'Athletics', value: 'Athletics' },
            { label: 'Swimming', value: 'Swimming' },
            { label: 'Other', value: 'Other' }
        ],
    },
    league: {
        type: 'select',
        label: 'League',
        required: true,
        placeholder: 'Select a league',
        options: []


    },
    homeTeam: {
        type: 'text',
        label: 'Home Team',
        required: true,
        placeholder: 'Enter home team name',
        validation: {
            minLength: 2,
            maxLength: 100,
        },
    },
    awayTeam: {
        type: 'text',
        label: 'Away Team',
        required: true,
        placeholder: 'Enter away team name',
        validation: {
            minLength: 2,
            maxLength: 100,
        },
    },
    tip: {
        type: 'text',
        label: 'Prediction',
        required: true,
        placeholder: 'Enter your prediction (e.g., Home Win, Draw, Away Win)',
        validation: {
            minLength: 2,
            maxLength: 100,
        },
    },
    odds: {
        type: 'number',
        label: 'Odds',
        placeholder: 'Enter odds for the prediction',
        validation: {
            min: 1,
            max: 1000,
        },
    },
    analysis: {
        type: 'textarea',
        label: 'Analysis',
        placeholder: 'Enter your analysis for the prediction',
        validation: {
            maxLength: 2000,
        },
    },
    publishedAt: {
        type: 'datetime-local',
        label: 'Match Date',
        placeholder: 'Select publication date and time',
        required: true,

    },
    isFree: {
        type: 'checkbox',
        label: 'Free Prediction',

    },
    result: {
        type: 'select',
        label: 'Result',
        options: [
            { label: 'Pending', value: PredictionResult.PENDING },
            { label: 'Won', value: PredictionResult.WON },
            { label: 'Lost', value: PredictionResult.LOST },
        ],
    },
    userId: {
        type: 'text',
        label: 'User ID',
        placeholder: 'Enter user ID',
        required: true,
        disabled: true,
        hidden: true,
    }
};
